# Generated by Django 3.1.1 on 2020-09-19 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.baseclass')),
                ('name', models.CharField(max_length=20, verbose_name='職種名')),
            ],
            bases=('schedule.baseclass',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.baseclass')),
                ('name', models.CharField(max_length=20, verbose_name='チーム名')),
            ],
            bases=('schedule.baseclass',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.baseclass')),
                ('name', models.CharField(max_length=20)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.job')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.team')),
            ],
            bases=('schedule.baseclass',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.baseclass')),
                ('name', models.CharField(max_length=20, verbose_name='患者氏名')),
                ('responsible_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.staff')),
            ],
            bases=('schedule.baseclass',),
        ),
        migrations.CreateModel(
            name='AvoidTime',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.baseclass')),
                ('avoid_reason', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.patient')),
            ],
            bases=('schedule.baseclass',),
        ),
        migrations.CreateModel(
            name='ApplyTime',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.baseclass')),
                ('apply_reason', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.patient')),
            ],
            bases=('schedule.baseclass',),
        ),
    ]
