# Generated by Django 3.1.1 on 2020-09-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytime',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_patient_id', to='schedule.patient'),
        ),
        migrations.AlterField(
            model_name='avoidtime',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoid_patient_id', to='schedule.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='responsible_staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_staff_id', to='schedule.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_id', to='schedule.job'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_id', to='schedule.team'),
        ),
        migrations.CreateModel(
            name='Fim',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.baseclass')),
                ('meal', models.IntegerField()),
                ('grooming', models.IntegerField()),
                ('bed_bath', models.IntegerField()),
                ('dressing_upper_body', models.IntegerField()),
                ('dressing_lower_body', models.IntegerField()),
                ('toilet_operation', models.IntegerField()),
                ('urination_control', models.IntegerField()),
                ('defecation_control', models.IntegerField()),
                ('bed_chair_wheelchair', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('bathtub_shower', models.IntegerField()),
                ('walking', models.IntegerField()),
                ('wheelchair', models.IntegerField()),
                ('stairs', models.IntegerField()),
                ('understanding', models.IntegerField()),
                ('front_out', models.IntegerField()),
                ('social_ac', models.IntegerField()),
                ('problem_solving', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('main_move_method', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fim_patient', to='schedule.patient')),
            ],
            bases=('schedule.baseclass',),
        ),
    ]
