# Generated by Django 3.1.1 on 2020-09-22 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200920_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('type', models.IntegerField(choices=[(1, '日勤'), (2, '公休'), (3, '早番'), (4, '遅番'), (5, '夜勤')], primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='fim',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fim_patient_id', to='schedule.patient'),
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_type', to='schedule.shifttype')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id', to='schedule.staff')),
            ],
        ),
    ]
