# Generated by Django 3.1.1 on 2020-09-28 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200922_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoidtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 14, 22, 50, 823835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avoidtime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='avoidtime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
